### ISSUE TITLE
Logout command crashes server when not logged in

### ISSUE THREAD

**Issue by mahlonsmith** [42wim/matterircd#117]
Built 0.13.0 manually on FreeBSD 11.0-RELEASE.

```
# ./matterircd -version
version: 0.13.0 
```

Backtrace:

```
DEBU[2017-07-22T19:00:00-07:00] <- PRIVMSG mattermost :logout                 module=matterircd
INFO[2017-07-22T19:00:00-07:00] logout as xxxxx (team: xxxx) on xxxx  module=matterircd
DEBU[2017-07-22T19:00:00-07:00] Executed &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"PRIVMSG", Params:[]string{"mattermost"}, Trailing:"logout", EmptyTrailing:false} <nil>  module=matterircd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x7b37d6]

goroutine 64 [running]:
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).Logout(0x0, 0x8ba541, 0x1d)
        /root/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:229 +0x56
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).logoutFromMattermost(0xc4201d8840, 0xc420440254, 0xc4200bb1e0)
        /root/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:72 +0x169
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.logout(0xc4201d8840, 0xc4201d88f0, 0xc42044a150, 0x0, 0x0)
        /root/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmservice.go:26 +0x2b
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc4201d8840, 0xc4201d88f0, 0xc420440254, 0x6)
        /root/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmservice.go:234 +0x3bc
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdPrivMsg
        /root/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:345 +0x99c
```

**Comment by 42wim** [comment]
Thanks for reporting, this has just been fixed in master 0.14.0-dev
