### ISSUE TITLE
crash using slack (2)

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#144]
similar to #143 but with clearly different stacktrace: just idling on slack gave me the following error, no idea what I did to cause it (altough I guess it has to do with my auto-away I guess):

panic: runtime error: invalid memory address or nil pointer dereference                                                           
[signal SIGSEGV: segmentation violation code=0x1 addr=0x71 pc=0x83c82d]                                                 
                                                                                                                                  
goroutine 142 [running]:                                                                                                          
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdAway(0x9c03e0, 0xc4200791e0, 0xc420178000, 0xc420232000, 0xc4200e3c28, 0x1)                                                                                         
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:39 +0x2d                      
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.commands.Run(0xc420163320, 0x9c03e0, 0xc4200791e0, 0xc420178000, 
0xc420232000, 0xc4201bbd78, 0xc420066240)                                                                                         
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/commands.go:51 +0x1d3       
github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).handle.func1(0xc4200791e0, 0xc420178000, 0xc420232000, 
0xc42068e100)                                                                                                                     
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:368 +0x7a                              
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*server).handle                                              /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server.go:367 +0x107

**Comment by Peter4825** [comment]
Seems I can reproduce this by setting myself away and then unsetting away...
