### ISSUE TITLE
Container crashes sometimes

### ISSUE THREAD

**Issue by madchap** [42wim/matterircd#176]
Hi,

Just had another occurence of this now, and decided to this time post the stacktrace. I don't know what it is coming from, seems to happen at random or something.

Running image

```
$ docker inspect --format='{{.Image}}' irc                                                                                                                                                 
sha256:48492e84fe0bbe37b6cf70dd555a8f421cb07b189b9fffb3970de177805bc8aa
```

Some previous messages:

```
time="2018-05-07T15:10:11Z" level=error msg="ChannelView update for uz4zox3rpp8qbeogsoospjtwzh failed: https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: model.client.connecting.app_error, Post https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: net/http: request canceled (Client.Timeout exceeded while awa
iting headers)" module=matterclient 
time="2018-05-07T15:33:56Z" level=error msg="ChannelView update for uz4zox3rpp8qbeogsoospjtwzh failed: https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: model.client.connecting.app_error, Post https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: net/http: request canceled (Client.Timeout exceeded while awa
iting headers)" module=matterclient 
time="2018-05-07T15:33:56Z" level=error msg="ChannelView update for uz4zox3rpp8qbeogsoospjtwzh failed: https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: model.client.connecting.app_error, Post https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: net/http: request canceled (Client.Timeout exceeded while awa
iting headers)" module=matterclient 
time="2018-05-07T18:44:15Z" level=error msg="ChannelView update for uz4zox3rpp8qbeogsoospjtwzh failed: https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: model.client.connecting.app_error, Post https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: net/http: request canceled (Client.Timeout exceeded while awa
iting headers)" module=matterclient 
time="2018-05-07T18:44:15Z" level=error msg="ChannelView update for uz4zox3rpp8qbeogsoospjtwzh failed: https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: model.client.connecting.app_error, Post https://mattermost.mydomain.com/api/v4/channels/members/xr1w8x6ryirrigkxmsfpuz8sxr/view: net/http: request canceled (Client.Timeout exceeded while awa
iting headers)" module=matterclient 

```

Stacktrace
```
time="2018-05-07T19:13:33Z" level=error msg="error:websocket: unexpected reserved bits 0x60" module=matterclient 
panic: runtime error: slice bounds out of range

goroutine 61704 [running]:
bufio.(*Reader).Read(0xc420652300, 0xc420d26000, 0x72, 0x2000, 0x0, 0xc420077480, 0xc4200774a8)
        /usr/lib/go/src/bufio/bufio.go:227 +0x3c1
io.(*LimitedReader).Read(0xc420362f60, 0xc420d26000, 0x2000, 0x2000, 0x7f6b48e2e9b8, 0x0, 0x0)
        /usr/lib/go/src/io/io.go:446 +0x65
io/ioutil.devNull.ReadFrom(0x0, 0x55a772d26260, 0xc420362f60, 0x55a772ca46e0, 0xc42013fb01, 0x7f6b48e2e9b8)
        /usr/lib/go/src/io/ioutil/ioutil.go:147 +0x94
io.copyBuffer(0x55a772d26e20, 0x55a772f9d128, 0x55a772d26260, 0xc420362f60, 0x0, 0x0, 0x0, 0x55a772cb8d80, 0x1, 0xc420362f60)
        /usr/lib/go/src/io/io.go:386 +0x31c
io.Copy(0x55a772d26e20, 0x55a772f9d128, 0x55a772d26260, 0xc420362f60, 0xc420018360, 0x55a7724fd146, 0x3)
        /usr/lib/go/src/io/io.go:362 +0x5c
io.CopyN(0x55a772d26e20, 0x55a772f9d128, 0x55a772d25d40, 0xc420652300, 0x72, 0xc42013fd40, 0x55a77251bb06, 0x55a772d23c88)
        /usr/lib/go/src/io/io.go:338 +0x8d
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).advanceFrame(0xc422a1e780, 0x0, 0x0, 0x0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:771 +0xd64
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc422a1e780, 0xc42013fe88, 0x55a7724f6175, 0xc420284000, 0xc42013ff18, 0x55a7728d7401)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:938 +0xa5
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).ReadMessage(0xc422a1e780, 0xc42013ff18, 0x15, 0xc42013ff38, 0x1, 0x1, 0x0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:1019 +0x31
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc420288000)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:266 +0x61
created by github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).StatusLoop
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:831 +0x3b8
```

Let me know what kind of other information I can provide.

Thank you.
Best,
fred

**Comment by 42wim** [comment]
Hi thanks for reporting.
I've upgraded the websocket library in master, it contains a lot of bugfixes and hopefully also fixes your issue.

If this is not the case, feel free to reopen.
