### ISSUE TITLE
panic on websocket

### ISSUE THREAD

**Issue by purpleidea** [42wim/matterircd#189]
AFAICT I noticed this after an internet outage. Everything came back except slack, and when I looked this is what I found. Version is in the logs. HTH

```
$ ./bin/matterircd
INFO[2018-06-11T11:21:02-04:00] Running version 0.17.3                        module=matterircd
INFO[2018-06-11T11:21:02-04:00] Listening on 127.0.0.1:6667                   module=matterircd
INFO[2018-06-11T11:21:40-04:00] New connection: 127.0.0.1:47096               module=matterircd
panic: repeated read on failed websocket connection

goroutine 14 [running]:
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).NextReader(0xc420094b40, 0xffffffffffffffff, 0x0, 0xc420275ec0, 0xc420275ec0, 0x412058)
        /home/james/code/gopath/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/conn.go:958 +0x35d
github.com/42wim/matterircd/vendor/github.com/gorilla/websocket.(*Conn).ReadJSON(0xc420094b40, 0x8dff00, 0xc420338a80, 0x1, 0x1)
        /home/james/code/gopath/src/github.com/42wim/matterircd/vendor/github.com/gorilla/websocket/json.go:45 +0x2f
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).receiveIncomingEvent(0xc4200c69a0)
        /home/james/code/gopath/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:292 +0xa1
github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).handleIncomingEvents(0xc4200c69a0, 0xc420206d20)
        /home/james/code/gopath/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:227 +0x2d
created by github.com/42wim/matterircd/vendor/github.com/nlopes/slack.(*RTM).ManageConnection
        /home/james/code/gopath/src/github.com/42wim/matterircd/vendor/github.com/nlopes/slack/websocket_managed_conn.go:54 +0x24d
```

**Comment by 42wim** [comment]
Same issue as https://github.com/nlopes/slack/issues/338

**Comment by 42wim** [comment]
As per IRC, this should be fixed now? reopen if needed

**Comment by james-lawrence** [comment]
@42wim what was the resolution?
