### ISSUE TITLE
nil pointer dereference in mm-go-irckit.CmdPrivMsg

### ISSUE THREAD

**Issue by dansimau** [42wim/matterircd#247]
Looks like maybe the connection to mattermost was closed while handling a message?

```
time="2019-04-22T20:34:24+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:34:29+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:34:35+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:34:41+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:34:47+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:34:52+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:34:58+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:35:02+02:00" level=error msg="Connection is not alive: &model.AppError{Id:"api.context.session_expired.app_error", Message:"Invalid or expired session, please login again.", DetailedError:"", RequestId:"xxx", StatusCode:401, Where:"", IsOAuth:false, params:map[string]interface {}(nil)}" prefix=matterclient
time="2019-04-22T20:35:04+02:00" level=error msg="error:websocket: close 1006 (abnormal closure): unexpected EOF" prefix=matterclient
time="2019-04-22T20:35:07+02:00" level=error msg="error:read tcp x.x.x.x:41470->x.x.x.x:443: use of closed network connection" prefix=matterclient
time="2019-04-22T20:35:11+02:00" level=info msg="Found version 5.3.0.176.a3c193a71ee9fbf13414276ab52fbb69.true" prefix=matterclient
time="2019-04-22T20:35:12+02:00" level=error msg="Login failed: &model.AppError{Id:"api.context.session_expired.app_error", Message:"Invalid or expired session, please login again.", DetailedError:"", RequestId:"xxx", StatusCode:401, Where:"", IsOAuth:false, params:map[string]interface {}(nil)}" prefix=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8eedff]

goroutine 67450 [running]:
github.com/42wim/matterircd/mm-go-irckit.CmdPrivMsg(0xb2b8a0, 0xc00110e000, 0xc001bb7b80, 0xc0001d6280, 0xc0001ef100, 0xc0004b4001)
        /home/dan/.go/src/github.com/42wim/matterircd/mm-go-irckit/server_commands.go:455 +0x2af
github.com/42wim/matterircd/mm-go-irckit.commands.Run(0xc000fca060, 0xb2b8a0, 0xc00110e000, 0xc001bb7b80, 0xc0001d6280, 0x0, 0x0)
        /home/dan/.go/src/github.com/42wim/matterircd/mm-go-irckit/commands.go:57 +0x159
github.com/42wim/matterircd/mm-go-irckit.(*server).handle.func1(0xc00110e000, 0xc001bb7b80, 0xc0000100b8)
        /home/dan/.go/src/github.com/42wim/matterircd/mm-go-irckit/server.go:365 +0x7d
created by github.com/42wim/matterircd/mm-go-irckit.(*server).handle
        /home/dan/.go/src/github.com/42wim/matterircd/mm-go-irckit/server.go:364 +0x108
```

**Comment by 42wim** [comment]
What version or commit of matterircd are you running ?

**Comment by dansimau** [comment]
version: 0.19.3-dev
commit 8e043ed

**Comment by 42wim** [comment]
Thanks for reporting!
Fixed in master
