### ISSUE TITLE
Segfault on portbind permission error

### ISSUE THREAD

**Issue by setpill** [42wim/matterircd#257]
```
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=info msg="Loaded config from $CONFDIR/matterircd.toml" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=info msg="enabling debug" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=info msg="Running version 0.19.2 091f927" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=info msg="Listening on $MATTERIRCD_HOST_NAME:6697 (TLS)" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=info msg="TLS listening on $MATTERIRCD_HOST_NAME:6697" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=error msg="Can not listen on $MATTERIRCD_HOST_NAME:667: listen tcp 127.0.1.1:667: bind: permission denied" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: time="$DATETIME" level=info msg="Listening on $MATTERIRCD_HOST_NAME:667" module=matterircd
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: panic: runtime error: invalid memory address or nil pointer dereference
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8fb7c9]
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: goroutine 7 [running]:
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: main.main.func2()
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]:         /go/src/github.com/42wim/matterircd/main.go:98 +0x159
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]: created by main.main
$DATETIME $MATTERIRCD_HOST_NAME matterircd[304]:         /go/src/github.com/42wim/matterircd/main.go:92 +0xaa1
$DATETIME $MATTERIRCD_HOST_NAME systemd[1]: matterircd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
$DATETIME $MATTERIRCD_HOST_NAME systemd[1]: matterircd.service: Failed with result 'exit-code'.
```

**Comment by 42wim** [comment]
Thanks for reporting, closed in master
