### ISSUE TITLE
expired session panic

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#259]
Running matterircd 0.19.2, official release, after quite some uptime/usage, my mattermost crashed with the following in the log:

```
time="2019-08-26T08:21:06+02:00" level=error msg="ChannelView update for m1538yu6mtnm8ks66bmser8zdr failed: : Invalid or expired session, please login again., " prefix=matterclient
time="2019-08-26T08:21:06+02:00" level=error msg="ChannelView update for jro8144hd7baursoc7o8nuw5co failed: : Invalid or expired session, please login again., " prefix=matterclient
panic: runtime error: index out of range

goroutine 182 [running]:
github.com/42wim/matterircd/mm-go-irckit.(*User).handleSlackActionPost(0xc0001b8780, 0xc0008b8d80)
        /go/src/github.com/42wim/matterircd/mm-go-irckit/slackuser.go:431 +0x19bd
github.com/42wim/matterircd/mm-go-irckit.(*User).handleSlack(0xc0001b8780)
        /go/src/github.com/42wim/matterircd/mm-go-irckit/slackuser.go:286 +0x185
created by github.com/42wim/matterircd/mm-go-irckit.(*User).loginToSlack
        /go/src/github.com/42wim/matterircd/mm-go-irckit/slackuser.go:141 +0x392
```

Contact me on irc if you need more from the logfile :)

**Comment by 42wim** [comment]
Fixed in master
