### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in mm-go-irckit.(*User).handleSlackActionPost

### ISSUE THREAD

**Issue by stintel** [42wim/matterircd#263]
```
time="2019-11-18T10:01:00+01:00" level=info msg="New connection: 127.0.0.1:48512" module=matterircd
in handshake &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"CAP", Params:[]string{"LS"}, Trailing:"", EmptyTrailing:false}
in handshake &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"PASS", Params:[]string{""}, Trailing:"", EmptyTrailing:false}
in handshake &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"NICK", Params:[]string{"stijn.tintel"}, Trailing:"", EmptyTrailing:false}
in handshake &irc.Message{Prefix:(*irc.Prefix)(nil), Command:"USER", Params:[]string{"stijn", "stijn", "127.0.0.1"}, Trailing:"Stijn Tintel", EmptyTrailing:false}
1
1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8aa853]

goroutine 9 [running]:
github.com/42wim/matterircd/mm-go-irckit.(*User).handleSlackActionPost(0xc4200efcc0, 0xc4200cc280)
        /var/tmp/portage/net-irc/matterircd-0.19.3/work/matterircd-0.19.3/src/github.com/42wim/matterircd/mm-go-irckit/slackuser.go:560 +0xd73
github.com/42wim/matterircd/mm-go-irckit.(*User).handleSlack(0xc4200efcc0)
        /var/tmp/portage/net-irc/matterircd-0.19.3/work/matterircd-0.19.3/src/github.com/42wim/matterircd/mm-go-irckit/slackuser.go:303 +0x1ec
created by github.com/42wim/matterircd/mm-go-irckit.(*User).loginToSlack
        /var/tmp/portage/net-irc/matterircd-0.19.3/work/matterircd-0.19.3/src/github.com/42wim/matterircd/mm-go-irckit/slackuser.go:141 +0x447
```

**Comment by 42wim** [comment]
Is this reproduceable or just happening sometimes?

**Comment by 42wim** [comment]
Made a hotfix for this so it can't panic there anymore and will report an error.
Please paste the error here if you get hit again.
