### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by sabaini** [42wim/matterircd#286]
Got the below error after running matterircd for some days. This is matterircd-0.19.4-linux-64bit running on Ubuntu 16.04.6 LTS (lxc container)

```
panic: runtime error: slice bounds out of range [:8192] with capacity 4096 [recovered]
        panic: runtime error: slice bounds out of range [:8192] with capacity 4096

goroutine 18831 [running]:
io/ioutil.readAll.func1(0xc0004e9e58)
        /usr/local/go/src/io/ioutil/ioutil.go:30 +0x101
panic(0xa32c80, 0xc000784e20)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
bufio.(*Reader).Read(0xc0005ced80, 0xc0004ce08d, 0x1000, 0x1d73, 0x91, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:237 +0x3f0
github.com/gorilla/websocket.(*messageReader).Read(0xc000096138, 0xc0004ce08d, 0x1d73, 0x1d73, 0x91, 0x0, 0x0)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:1021 +0x1ee
bytes.(*Buffer).ReadFrom(0xc0004e9df0, 0x7fac20386398, 0xc000096138, 0x9df3e0, 0x9d7f20, 0xc0000b0d00)
        /usr/local/go/src/bytes/buffer.go:204 +0xb4
io/ioutil.readAll(0x7fac20386398, 0xc000096138, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/io/ioutil/ioutil.go:36 +0x100
io/ioutil.ReadAll(...)
        /usr/local/go/src/io/ioutil/ioutil.go:45
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc0004231e0, 0xe6, 0x600, 0x9f2640, 0xc0004b3c50, 0x0, 0x0)
        /go/pkg/mod/github.com/gorilla/websocket@v1.4.1/conn.go:1068 +0x9a
github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc0000b0370)
        /go/pkg/mod/github.com/42wim/matterbridge@v1.16.1-0.20190921223437-da3868c104f9/matterclient/matterclient.go:200 +0x5b
created by github.com/42wim/matterbridge/matterclient.(*MMClient).StatusLoop
        /go/pkg/mod/github.com/42wim/matterbridge@v1.16.1-0.20190921223437-da3868c104f9/matterclient/matterclient.go:276 +0x3d1
```

**Comment by 42wim** [comment]
could you try master, there has been a lot of refactoring and this could also be fixed.
Feel free to reopen if this is not the case.
