### ISSUE TITLE
matterircd crashes after joining first channel

### ISSUE THREAD

**Issue by maciejjo** [42wim/matterircd#30]
I am able to run matterircd, it connects to server, but when i do LOGIN, it joins one channel and the binary crashes. I attach debug log of matterircd with traces from go:

```
[12:38:39][maciejjo@fireball:matterircd][0]$ ./matterircd -port=6669 -mmserver="10.157.66.93" -mminsecure=true -mmteam="myteam" -debug=true
2016-01-28 12:38:42.365 INFO enabling debug
2016-01-28 12:38:50.660 INFO New connection: 127.0.0.1:34806
2016-01-28 12:38:50.666 DEBUG <- CAP LS
2016-01-28 12:38:50.666 DEBUG <- NICK maciejjo
2016-01-28 12:38:50.667 DEBUG <- USER maciejjo maciejjo localhost :Maciej Sobkowski
2016-01-28 12:38:50.667 DEBUG -> :matterircd 001 maciejjo :Welcome! maciejjo!maciejjo@localhost
2016-01-28 12:38:50.667 DEBUG -> :matterircd 002 maciejjo :Your host is matterircd, running version 0.2
2016-01-28 12:38:50.667 DEBUG -> :matterircd 003 maciejjo :This server was created Thu Jan 28 12:38:50 CET 2016
2016-01-28 12:38:50.667 DEBUG -> :matterircd 004 maciejjo :matterircd 0.2 o o
2016-01-28 12:38:50.667 DEBUG -> :matterircd 251 maciejjo :There are 2 users and 0 services on 1 servers
2016-01-28 12:38:50.667 DEBUG -> :matterircd 375 maciejjo :- matterircd Message of the Day -
2016-01-28 12:38:50.667 DEBUG -> :matterircd 376 maciejjo :End of /MOTD command.
2016-01-28 12:38:50.678 DEBUG <- MODE maciejjo +i
2016-01-28 12:38:53.543 DEBUG <- PING matterircd
2016-01-28 12:38:53.543 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:39:54.600 DEBUG <- PING matterircd
2016-01-28 12:39:54.600 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:40:55.665 DEBUG <- PING matterircd
2016-01-28 12:40:55.665 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:41:56.720 DEBUG <- PING matterircd
2016-01-28 12:41:56.720 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:42:57.778 DEBUG <- PING matterircd
2016-01-28 12:42:57.778 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:43:58.836 DEBUG <- PING matterircd
2016-01-28 12:43:58.836 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:44:59.883 DEBUG <- PING matterircd
2016-01-28 12:44:59.883 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:45:43.523 DEBUG <- PRIVMSG mattermost :login
2016-01-28 12:45:43.523 DEBUG -> :mattermost!mattermost@service PRIVMSG maciejjo :need LOGIN <login> <pass>
2016-01-28 12:45:57.923 DEBUG <- PRIVMSG mattermost :login mail@example.com ********
2016-01-28 12:45:57.923 DEBUG retrying login myteam mail@example.com 10.157.66.93
2016-01-28 12:46:00.929 DEBUG <- PING matterircd
2016-01-28 12:46:00.929 DEBUG -> :matterircd PONG matterircd
2016-01-28 12:46:01.547 DEBUG -> :maciejjo!maciejjo@localhost JOIN #mychannel
2016-01-28 12:46:01.548 DEBUG -> :matterircd 353 maciejjo = #mychannel :maciejjo
2016-01-28 12:46:01.548 DEBUG -> :matterircd 366 maciejjo #mychannel :End of /NAMES list.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20]

goroutine 32 [running]:
irckit.$nested0
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/mmuser.go:150
created by github_com_42wim_mm_go_irckit.addUsersToChannels.pN34_github_com_42wim_mm_go_irckit.User
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/mmuser.go:138

goroutine 16 [IO wait, 5 minutes]:
net.runtime_pollWait
        /build/gcc/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.accept.pN9_net.netFD
        /build/gcc/src/gcc-5.3.0/libgo/go/net/fd_unix.go:419
net.AcceptTCP.pN15_net.TCPListener
        /build/gcc/src/gcc-5.3.0/libgo/go/net/tcpsock_posix.go:234
net.Accept.pN15_net.TCPListener
        /build/gcc/src/gcc-5.3.0/libgo/go/net/tcpsock_posix.go:244
main.start
        /home/maciejjo/code/matterircd/main.go:46
main.main
        /home/maciejjo/code/matterircd/main.go:41

goroutine 18 [finalizer wait, 5 minutes]:
created by runtime_createfing
        /build/gcc/src/gcc-5.3.0/libgo/runtime/mgc0.c:2572

goroutine 19 [chan receive, 5 minutes]:
github_com_alecthomas_log4go.run.pN45_github_com_alecthomas_log4go.ConsoleLogWriter
        /home/maciejjo/code/golang/src/github.com/alecthomas/log4go/termlog.go:33
created by github_com_alecthomas_log4go.NewConsoleLogWriter
        /home/maciejjo/code/golang/src/github.com/alecthomas/log4go/termlog.go:26

goroutine 27 [chan receive]:
github_com_42wim_mm_go_irckit.addUsersToChannels.pN34_github_com_42wim_mm_go_irckit.User
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/mmuser.go:137
github_com_42wim_mm_go_irckit.loginToMattermost.pN34_github_com_42wim_mm_go_irckit.User
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/mmuser.go:107
github_com_42wim_mm_go_irckit.handleMMServiceBot.pN34_github_com_42wim_mm_go_irckit.User
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/mmuser.go:527
created by github_com_42wim_mm_go_irckit.handle.pN36_github_com_42wim_mm_go_irckit.server
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/server.go:783

goroutine 22 [runnable]:
net.runtime_pollWait
        /build/gcc/src/gcc-5.3.0/libgo/runtime/netpoll.goc:151
net.Wait.pN12_net.pollDesc
        /build/gcc/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:84
net.WaitRead.pN12_net.pollDesc
        /build/gcc/src/gcc-5.3.0/libgo/go/net/fd_poll_runtime.go:89
net.Read.pN9_net.netFD
        /build/gcc/src/gcc-5.3.0/libgo/go/net/fd_unix.go:242
net.Read.pN8_net.conn
        /build/gcc/src/gcc-5.3.0/libgo/go/net/net.go:121
net.Read.pN11_net.TCPConn
        /build/gcc/src/gcc-5.3.0/libgo/go/net/tcpsock_posix.go:57
bufio.fill.pN12_bufio.Reader
        /build/gcc/src/gcc-5.3.0/libgo/go/bufio/bufio.go:97
bufio.ReadSlice.pN12_bufio.Reader
        /build/gcc/src/gcc-5.3.0/libgo/go/bufio/bufio.go:295
bufio.ReadBytes.pN12_bufio.Reader
        /build/gcc/src/gcc-5.3.0/libgo/go/bufio/bufio.go:374
bufio.ReadString.pN12_bufio.Reader
        /build/gcc/src/gcc-5.3.0/libgo/go/bufio/bufio.go:414
github_com_sorcix_irc.Decode.pN29_github_com_sorcix_irc.Decoder
        /home/maciejjo/code/golang/src/github.com/sorcix/irc/stream.go:80
github_com_42wim_mm_go_irckit.Decode.N34_github_com_42wim_mm_go_irckit.conn
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/net.go:20
github_com_42wim_mm_go_irckit.Decode.pN34_github_com_42wim_mm_go_irckit.User
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/user.go:137
github_com_42wim_mm_go_irckit.handle.pN36_github_com_42wim_mm_go_irckit.server
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/server.go:581
created by github_com_42wim_mm_go_irckit.Connect.pN36_github_com_42wim_mm_go_irckit.server
        /home/maciejjo/code/golang/src/github.com/42wim/mm-go-irckit/server.go:282

goroutine 29 [select]:
net_http.readLoop.pN20_net_http.persistConn
        /build/gcc/src/gcc-5.3.0/libgo/go/net/http/transport.go:928
created by net_http.dialConn.pN18_net_http.Transport
        /build/gcc/src/gcc-5.3.0/libgo/go/net/http/transport.go:660

goroutine 30 [select]:
net_http.writeLoop.pN20_net_http.persistConn
        /build/gcc/src/gcc-5.3.0/libgo/go/net/http/transport.go:945
created by net_http.dialConn.pN18_net_http.Transport
        /build/gcc/src/gcc-5.3.0/libgo/go/net/http/transport.go:661
```

**Comment by 42wim** [comment]
Hm strange, you're building from master branch?
And are you running the latest mattermost version?

**Comment by maciejjo** [comment]
Yes, building from master. I have Mattermost 1.3.0, from what I see there is 1.4.0 available - but I don't control the server, so I can't update.

**Comment by 42wim** [comment]
Would you mind trying the binaries and see if it happens there also?
If you don't trust the binaries, to build it yourself
```
cd /$GOPATH/src/github.com/mattermost/platform
git checkout v1.3.0
```
edit model/client.go and change the l4g path to "github.com/alecthomas/log4go"
```
cd /$GOPATH/src/github.com/42wim/mm-go-irckit
git checkout 2a881c08007ed4b714bea4ae5cbe0f25f2cdac77
cd /$GOPATH/src/github.com/42wim/matterircd
go build
```
Let me know if either of those fixed it

**Comment by maciejjo** [comment]
until I did the second checkout I had build error, after this it builds without problem and also doesn't crash anymore :+1:
