### ISSUE TITLE
crash on reconnect

### ISSUE THREAD

**Issue by Peter4825** [42wim/matterircd#309]
NOTE: this is on a self-built version of 2020-08-12's tree status

```
time="2020-08-26T09:55:46+02:00" level=debug msg="<- QUIT :Reconnecting" module=matterircd
time="2020-08-26T09:55:46+02:00" level=debug msg="-> :matterircd QUIT :Reconnecting" module=matterircd
time="2020-08-26T09:55:46+02:00" level=debug msg="-> :matterircd ERROR :You will be missed." module=matterircd
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa0 pc=0xa71f51]

goroutine 33053 [running]:
github.com/42wim/matterircd/mm-go-irckit.CmdQuit(0xd66d80, 0xc000168dd0, 0xc000168ea0, 0xc000d7cfa0, 0xc000222478, 0xc000279301)
        /home/peter/.programs/gopath/src/github.com/42wim/matterircd/mm-go-irckit/server_commands.go:398 +0xf1
github.com/42wim/matterircd/mm-go-irckit.commands.Run(0xc00015d590, 0xd66d80, 0xc000168dd0, 0xc000168ea0, 0xc000d7cfa0, 0x40b14b, 0xc000b04000)
        /home/peter/.programs/gopath/src/github.com/42wim/matterircd/mm-go-irckit/commands.go:55 +0x12e
github.com/42wim/matterircd/mm-go-irckit.(*server).handle.func1(0xc000168dd0, 0xc000168ea0, 0xc000d7cfa0)
        /home/peter/.programs/gopath/src/github.com/42wim/matterircd/mm-go-irckit/server.go:347 +0x7a
created by github.com/42wim/matterircd/mm-go-irckit.(*server).handle
        /home/peter/.programs/gopath/src/github.com/42wim/matterircd/mm-go-irckit/server.go:346 +0xe2
```

**Comment by 42wim** [comment]
Already been fixed, there has been lots of stability fixes since 12/08, please use latest master
