### ISSUE TITLE
matterircd crashed - possibly because of idling

### ISSUE THREAD

**Issue by weipe** [42wim/matterircd#318]
Version: 0.20.0 7954242
OS: Ubuntu 20.04.1 LTS

I ran into this crash today. If I recall correctly, I had been idling for some time, if that matters. The network itself is stable, so I don't think it's because of a flaky connection.

```
[7159]  INFO matterclient: reconnect successful
[7175] ERROR matterclient: got a ping timeout
[7175]  INFO matterclient: reconnect: logout
panic: send on closed channel

goroutine 115185 [running]:
github.com/mattermost/mattermost-server/v5/model.(*WebSocketClient).SendMessage(...)
	/go/pkg/mod/github.com/mattermost/mattermost-server/v5@v5.25.2/model/websocket_client.go:252
github.com/42wim/matterircd/pkg/matterclient.(*Client).doCheckAlive(0xc000262180, 0xc0016bef48, 0x2)
	/go/src/github.com/42wim/matterircd/pkg/matterclient/matterclient.go:500 +0xf1
github.com/42wim/matterircd/pkg/matterclient.(*Client).checkAlive(0xc000262180, 0xa3e420, 0xc003fad500)
	/go/src/github.com/42wim/matterircd/pkg/matterclient/matterclient.go:525 +0x12e
created by github.com/42wim/matterircd/pkg/matterclient.(*Client).checkConnection
	/go/src/github.com/42wim/matterircd/pkg/matterclient/matterclient.go:537 +0x6e
```

Let me also say that I am an extremely grateful fan of this project - matterircd is making my work life 1000% better - THANK YOU!

**Comment by 42wim** [comment]
This is now probably fixed in master :-)
