### ISSUE TITLE
crash on login

### ISSUE THREAD

**Issue by maxandersen** [42wim/matterircd#39]
I get a crash when I msg my login with correct credentials (if I use wrong ones it tells me ;)

```
~ ❯❯❯ docker run -it -p 6667:6667 --name ircd --link mattermost-dev:mm xyproto/matterircd -mmserver mm -mmteam maxandersen -interface 0.0.0.0 -debug -mminsecure=true
2016-03-19 21:45:05.095 INFO enabling debug
2016-03-19 21:45:20.171 INFO New connection: 192.168.99.1:64986
2016-03-19 21:45:20.181 DEBUG <- CAP LS 302
2016-03-19 21:45:20.185 DEBUG <- NICK maxandersen
2016-03-19 21:45:20.190 DEBUG <- USER maxandersen 0 * :Max Rydahl Andersen
2016-03-19 21:45:20.190 DEBUG -> :matterircd 001 maxandersen :Welcome! maxandersen!maxandersen@192.168.99.1
2016-03-19 21:45:20.191 DEBUG -> :matterircd 002 maxandersen :Your host is matterircd, running version 0.3
2016-03-19 21:45:20.191 DEBUG -> :matterircd 003 maxandersen :This server was created Sat Mar 19 21:45:20 UTC 2016
2016-03-19 21:45:20.192 DEBUG -> :matterircd 004 maxandersen :matterircd 0.3 o o
2016-03-19 21:45:20.192 DEBUG -> :matterircd 251 maxandersen :There are 2 users and 0 services on 1 servers
2016-03-19 21:45:20.193 DEBUG -> :matterircd 375 maxandersen :- matterircd Message of the Day -
2016-03-19 21:45:20.193 DEBUG -> :matterircd 376 maxandersen :End of /MOTD command.
2016-03-19 21:45:29.544 DEBUG <- HELP
2016-03-19 21:45:49.512 DEBUG <- JOIN #off-topic
2016-03-19 21:45:49.512 DEBUG -> :matterircd 473 :Cannot join channel (+i)
2016-03-19 21:45:54.620 DEBUG <- JOIN #max
2016-03-19 21:45:54.620 DEBUG -> :matterircd 473 :Cannot join channel (+i)
2016-03-19 21:46:02.675 DEBUG <- JOIN #townsquare
2016-03-19 21:46:02.676 DEBUG -> :matterircd 473 :Cannot join channel (+i)
2016-03-19 21:46:13.777 DEBUG <- PRIVMSG mattermost :login test@xam.dk secret
2016-03-19 21:46:13.777 DEBUG retrying login maxandersen test@xam.dk mm
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x591d2b]

goroutine 9 [running]:
github.com/mattermost/platform/model.(*Client).login(0xc820051720, 0xc8200c3110, 0xc82003ebb8, 0xc82003eba8)
	/go/src/github.com/mattermost/platform/model/client.go:308 +0x53b
github.com/mattermost/platform/model.(*Client).LoginByEmail(0xc820051720, 0x7ffd8a5b4c8f, 0xb, 0xc8200c303a, 0xb, 0xc8200c3046, 0x8, 0xc81ffff53f, 0x43fa05)
	/go/src/github.com/mattermost/platform/model/client.go:280 +0x16a
github.com/42wim/mm-go-irckit.(*User).loginToMattermost(0xc8200b6750, 0x0, 0x0)
	/go/src/github.com/42wim/mm-go-irckit/mmuser.go:54 +0x59f
github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc8200b6750, 0xc8200b6820, 0xc8200c3034, 0x1a)
	/go/src/github.com/42wim/mm-go-irckit/mmuser.go:527 +0xdfe
created by github.com/42wim/mm-go-irckit.(*server).handle
	/go/src/github.com/42wim/mm-go-irckit/server.go:783 +0x520a

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7fe03f6d8ac8, 0x72, 0xc820010160)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200e2f40, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200e2f40, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8200e2ee0, 0x0, 0x7fe03f6d8b88, 0xc82000fa60)
	/usr/local/go/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200260f0, 0xc8200e1d70, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net.(*TCPListener).Accept(0xc8200260f0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/tcpsock_posix.go:264 +0x3d
main.start(0x7fe03f6d7b48, 0xc8200260f0)
	/go/src/github.com/42wim/matterircd/main.go:46 +0x4e
main.main()
	/go/src/github.com/42wim/matterircd/main.go:41 +0x8a9

goroutine 5 [chan receive]:
github.com/alecthomas/log4go.(*ConsoleLogWriter).run(0xc82000e660, 0x7fe03f6d7330, 0xc820026010)
	/go/src/github.com/alecthomas/log4go/termlog.go:33 +0x69
created by github.com/alecthomas/log4go.NewConsoleLogWriter
	/go/src/github.com/alecthomas/log4go/termlog.go:26 +0xb5

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7fe03f6d8a08, 0x72, 0xc820010160)
	/usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200e2fb0, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200e2fb0, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200e2f50, 0xc8200ea000, 0x1000, 0x1000, 0x0, 0x7fe03f6d3050, 0xc820010160)
	/usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200260f8, 0xc8200ea000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
bufio.(*Reader).fill(0xc8200187e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc8200187e0, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:328 +0x21a
bufio.(*Reader).ReadBytes(0xc8200187e0, 0xc82000fa0a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:406 +0xa9
bufio.(*Reader).ReadString(0xc8200187e0, 0x7d680a, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:446 +0x4d
github.com/sorcix/irc.(*Decoder).Decode(0xc82000fae0, 0x0, 0x0, 0x0)
	/go/src/github.com/sorcix/irc/stream.go:80 +0x59
github.com/42wim/mm-go-irckit.(*User).Decode(0xc8200b6750, 0x9ef4d8, 0x0, 0x0)
	/go/src/github.com/42wim/mm-go-irckit/user.go:137 +0xab
github.com/42wim/mm-go-irckit.(*server).handle(0xc8200b6680, 0xc8200b6750)
	/go/src/github.com/42wim/mm-go-irckit/server.go:581 +0xb1
created by github.com/42wim/mm-go-irckit.(*server).Connect
	/go/src/github.com/42wim/mm-go-irckit/server.go:282 +0xb5

goroutine 12 [select]:
net/http.(*persistConn).readLoop(0xc8200e86e0)
	/usr/local/go/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 13 [select]:
net/http.(*persistConn).writeLoop(0xc8200e86e0)
	/usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:686 +0xc9d
```

**Comment by maxandersen** [comment]
also - would be nice if logs didn't contain clear text passwords ;)

**Comment by 42wim** [comment]
What version of mattermost? If you're running mattermost master (>14march), you'll also need matterircd master

**Comment by maxandersen** [comment]
latest docker images of mattermost and matterirc.

**Comment by 42wim** [comment]
Specify the mattermost 2.0 version when starting the image , see https://github.com/42wim/matterircd/issues/38 for more info

**Comment by maxandersen** [comment]
That did it! thanks.
