### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by stintel** [42wim/matterircd#428]
Not sure what triggered it but this morning I hit this with 0.24.0:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x82bbbe]

goroutine 15 [running]:
github.com/42wim/matterircd/bridge/slack.(*Slack).handleSlack(0xc0002760c0)
        /var/tmp/portage/net-irc/matterircd-0.24.0/work/matterircd-0.24.0/src/github.com/42wim/matterircd/bridge/slack/slack.go:554 +0x5fe
created by github.com/42wim/matterircd/bridge/slack.(*Slack).loginToSlack
        /var/tmp/portage/net-irc/matterircd-0.24.0/work/matterircd-0.24.0/src/github.com/42wim/matterircd/bridge/slack/slack.go:503 +0x32e
```

**Comment by 42wim** [comment]
Fixed in master, not sure how this could happen, but I'm checking for nil pointers now anyways so it definitely can't happen anymore there :)
