### ISSUE TITLE
Crash with LOGIN <user> MMAUTHTOKENBLAH 

### ISSUE THREAD

**Issue by jmatsushita** [42wim/matterircd#55]
Here's the log!
```
irc-team_1 | 2016-07-02T17:25:16.328819355Z time="2016-07-02T17:25:16Z" level=debug msg="trying login with %!(EXTRA string=MMAUTHTOKEN)" module=matterclient 
irc-team_1 | 2016-07-02T17:25:16.331242025Z panic: runtime error: index out of range
irc-team_1 | 2016-07-02T17:25:16.331290588Z 
irc-team_1 | 2016-07-02T17:25:16.331310368Z goroutine 46 [running]:
irc-team_1 | 2016-07-02T17:25:16.331328042Z panic(0x924e80, 0xc820014020)
irc-team_1 | 2016-07-02T17:25:16.331346930Z 	/usr/lib/go/src/runtime/panic.go:481 +0x3e6
irc-team_1 | 2016-07-02T17:25:16.331365547Z github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient.(*MMClient).Login(0xc8201cd0e0, 0x0, 0x0)
irc-team_1 | 2016-07-02T17:25:16.331383051Z 	/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient/matterclient.go:94 +0x1fae
irc-team_1 | 2016-07-02T17:25:16.331399964Z github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost(0xc8201360f0, 0x7ffd7c47fc63, 0x0, 0x0)
irc-team_1 | 2016-07-02T17:25:16.331417277Z 	/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:64 +0x32e
irc-team_1 | 2016-07-02T17:25:16.331433999Z github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleMMServiceBot(0xc8201360f0, 0xc8201361e0, 0xc8201df414, 0x33)
irc-team_1 | 2016-07-02T17:25:16.331451103Z 	/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmservice.go:83 +0xf4d
irc-team_1 | 2016-07-02T17:25:16.331485209Z created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.CmdPrivMsg
irc-team_1 | 2016-07-02T17:25:16.331501720Z 	/go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/server_commands.go:283 +0xb25
```

**Comment by 42wim** [comment]
It should be used as MMAUTHTOKEN=yourtoken but thanks for fuzzing :-)
Fix will be added to the 0.8.1 release
