### ISSUE TITLE
crash after team leave

### ISSUE THREAD

**Issue by sheepherd** [42wim/matterircd#57]
When a user leaves the team, the whole ircd daemon crashes.
This happens with LDAP Auth, I can't check if it also applies to other login methods right now.

Is this already fixed in  v0.9.0-beta1? I'm not exactly sure if this is also meant by "Fix invalid team crashes"

Server: Debian GNU/Linux 8.5 (jessie)
Mattermost Version: Version: 3.2.0 Enterprise
Matterircd Version: 0.8.1

systemd service
---------------------

```
[Unit]
Description=Matterircd

[Service]
ExecStart=/opt/mattermost/bin/matterircd-linux64 -tlsbind xxxx:5566 -tlsdir /etc/ssl/xxxx -restrict xxxx -mmserver xxxx -mmteam xxxx

[Install]
WantedBy=multi-user.target
```

error logs
---------------------
```
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5fba6a]
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: goroutine 29 [running]:
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: panic(0x7d7040, 0xc420010040)
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: /usr/local/go/src/runtime/panic.go:500 +0x1a1
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient.(*MMClient).UpdateChannels(0xc4200537a0, 0xc420118c90, 0x5)
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient/matterclient.go:260 +0x4a
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient.(*MMClient).GetChannelName(0xc4200537a0, 0x0, 0x0, 0xc4201efec8,
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge-plus/matterclient/matterclient.go:273 +0x1a3
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).checkWsActionMessage(0xc4200d2870, 0xc420433b80)
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:304 +0xb6
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).handleWsMessage(0xc4200d2870)
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:173 +0x1b4
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
Aug 08 15:05:12 vm-adsy-messaging-01 matterircd-linux64[16816]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:73 +0x429
Aug 08 15:05:12 vm-adsy-messaging-01 systemd[1]: matterircd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Aug 08 15:05:12 vm-adsy-messaging-01 systemd[1]: Unit matterircd.service entered failed state.
```

config.json
---------------------

```
{
    "ServiceSettings": {
        "ListenAddress": ":8065",
        "MaximumLoginAttempts": 10,
        "SegmentDeveloperKey": "",
        "GoogleDeveloperKey": "",
        "EnableOAuthServiceProvider": false,
        "EnableIncomingWebhooks": false,
        "EnableOutgoingWebhooks": false,
        "EnableCommands": false,
        "EnableOnlyAdminIntegrations": true,
        "EnablePostUsernameOverride": false,
        "EnablePostIconOverride": false,
        "EnableTesting": false,
        "EnableDeveloper": false,
        "EnableSecurityFixAlert": true,
        "EnableInsecureOutgoingConnections": false,
        "EnableMultifactorAuthentication": false,
        "AllowCorsFrom": "",
        "SessionLengthWebInDays": 30,
        "SessionLengthMobileInDays": 30,
        "SessionLengthSSOInDays": 30,
        "SessionCacheInMinutes": 10,
        "WebsocketSecurePort": 443,
        "WebsocketPort": 80,
        "WebserverMode": "gzip",
        "EnableCustomEmoji": false,
        "RestrictCustomEmojiCreation": "all"
    },
    "TeamSettings": {
        "SiteName": "xxxxx",
        "MaxUsersPerTeam": 50,
        "EnableTeamCreation": false,
        "EnableUserCreation": false,
        "EnableOpenServer": false,
        "RestrictCreationToDomains": "xxxxx",
        "RestrictTeamNames": true,
        "EnableCustomBrand": true,
        "CustomBrandText": "xxxxx",
        "RestrictDirectMessage": "any",
        "RestrictTeamInvite": "all",
        "RestrictPublicChannelManagement": "all",
        "RestrictPrivateChannelManagement": "all"
    },
    "SqlSettings": {
        "DriverName": "postgres",
        "DataSource": "xxxxx",
        "DataSourceReplicas": [],
        "MaxIdleConns": 10,
        "MaxOpenConns": 10,
        "Trace": false,
        "AtRestEncryptKey": "xxxxx"
    },
    "LogSettings": {
        "EnableConsole": false,
        "ConsoleLevel": "DEBUG",
        "EnableFile": true,
        "FileLevel": "DEBUG",
        "FileFormat": "",
        "FileLocation": "logs/mattermost.log",
        "EnableWebhookDebugging": true
    },
    "PasswordSettings": {
        "MinimumLength": 5,
        "Lowercase": false,
        "Number": false,
        "Uppercase": false,
        "Symbol": false
    },
    "FileSettings": {
        "MaxFileSize": 52428800,
        "DriverName": "local",
        "Directory": "/opt/mattermost/data/",
        "EnablePublicLink": false,
        "PublicLinkSalt": "xxxxx",
        "ThumbnailWidth": 120,
        "ThumbnailHeight": 100,
        "PreviewWidth": 1024,
        "PreviewHeight": 0,
        "ProfileWidth": 128,
        "ProfileHeight": 128,
        "InitialFont": "luximbi.ttf",
        "AmazonS3AccessKeyId": "",
        "AmazonS3SecretAccessKey": "",
        "AmazonS3Bucket": "",
        "AmazonS3Region": "",
        "AmazonS3Endpoint": "",
        "AmazonS3BucketEndpoint": "",
        "AmazonS3LocationConstraint": false,
        "AmazonS3LowercaseBucket": false
    },
    "EmailSettings": {
        "EnableSignUpWithEmail": false,
        "EnableSignInWithEmail": false,
        "EnableSignInWithUsername": false,
        "SendEmailNotifications": true,
        "RequireEmailVerification": false,
        "FeedbackName": "Mattermost",
        "FeedbackEmail": "xxxxx",
        "FeedbackOrganization": "",
        "SMTPUsername": "xxxxxx",
        "SMTPPassword": "xxxxxx",
        "SMTPServer": "xxxxx",
        "SMTPPort": "587",
        "ConnectionSecurity": "",
        "InviteSalt": "xxxxxx",
        "PasswordResetSalt": "xxxxx",
        "SendPushNotifications": true,
        "PushNotificationServer": "https://push.mattermost.com",
        "PushNotificationContents": "full"
    },
    "RateLimitSettings": {
        "EnableRateLimiter": true,
        "PerSec": 10,
        "MemoryStoreSize": 10000,
        "VaryByRemoteAddr": true,
        "VaryByHeader": ""
    },
    "PrivacySettings": {
        "ShowEmailAddress": true,
        "ShowFullName": true
    },
    "SupportSettings": {
        "TermsOfServiceLink": "https://about.mattermost.com/default-terms/",
        "PrivacyPolicyLink": "https://about.mattermost.com/default-privacy-policy/",
        "AboutLink": "https://about.mattermost.com/default-about/",
        "HelpLink": "https://about.mattermost.com/default-help/",
        "ReportAProblemLink": "https://about.mattermost.com/default-report-a-problem/",
        "SupportEmail": "feedback@mattermost.com"
    },
    "GitLabSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    },
    "GoogleSettings": {
        "Enable": false,
        "Secret": "",
        "Id": "",
        "Scope": "",
        "AuthEndpoint": "",
        "TokenEndpoint": "",
        "UserApiEndpoint": ""
    },
    "LdapSettings": {
        "Enable": true,
        "LdapServer": "xxxxx",
        "LdapPort": xxxxx,
        "ConnectionSecurity": "",
        "BaseDN": "xxxxx",
        "BindUsername": "xxxx",
        "BindPassword": "xxxx",
        "UserFilter": "xxx",
        "FirstNameAttribute": "givenName",
        "LastNameAttribute": "sn",
        "EmailAttribute": "mailAlternativeAddress",
        "UsernameAttribute": "uid",
        "NicknameAttribute": "",
        "IdAttribute": "uid",
        "SyncIntervalMinutes": 60,
        "SkipCertificateVerification": false,
        "QueryTimeout": 60,
        "MaxPageSize": 0,
        "LoginFieldName": ""
    },
    "ComplianceSettings": {
        "Enable": false,
        "Directory": "./data/",
        "EnableDaily": false
    },
    "LocalizationSettings": {
        "DefaultServerLocale": "en",
        "DefaultClientLocale": "en",
        "AvailableLocales": ""
    },
    "SamlSettings": {
        "Enable": false,
        "Verify": false,
        "Encrypt": false,
        "IdpUrl": "",
        "IdpDescriptorUrl": "",
        "AssertionConsumerServiceURL": "",
        "IdpCertificateFile": "",
        "PublicCertificateFile": "",
        "PrivateKeyFile": "",
        "FirstNameAttribute": "",
        "LastNameAttribute": "",
        "EmailAttribute": "",
        "UsernameAttribute": "",
        "NicknameAttribute": "",
        "LocaleAttribute": "",
        "LoginButtonText": "With SAML"
    }
}
```

**Comment by 42wim** [comment]
No, the team fix is to fix a crash when specifying the wrong team. 
I can't seem to reproduce this issue, I made a team with a couple of users and let one users leave the team, worked fine here on 0.8.1 (but I don't have the enterprise edition)

Does this crash happen every time when a users leaves? or just sometimes ? 
Are you willing to test the 0.9.0-beta1 to see if it happens there too ?
Is it a very busy server (lots of users / messages) ? (could be a race condition somewhere)

Also your config.json contains some private credentials, don't know if they are obscured. (if not, you better change those)

**Comment by sheepherd** [comment]
I just tried to reproduce the issue and failed. But since I don't have direct access to the earlier user I cant' be sure the issue is gone yet.
As soon as I figure out if it still happens I will also try the 0.9.0-beta1 binary.
There are almost 40 users connected, I'm not sure if this counts as very busy.

**Comment by 42wim** [comment]
I'm going to close this for now. 
In the 0.9.0 release I handle the errors properly where you first crash occurred.
Feel free to reopen if it happens again.
