### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by badporcupine** [42wim/matterircd#97]
```
$ uname -a
Linux 2.6.32-5-xen-amd64 #1 SMP Mon Sep 23 23:29:01 UTC 2013 x86_64 GNU/Linux
```

```
INFO[2017-05-23T11:16:06+03:00] Running version 0.11.4 896895b                module=matterircd
INFO[2017-05-23T11:24:36+03:00] Found version 3.9.0.3.9.0.e112edb335cd1d5dc201c2526741de14.true  module=matterclient
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7b238f]

goroutine 26 [running]:
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).parseActionPost(0xc4200d59a0, 0xc42015cea0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:299 +0x4bf
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).parseMessage(0xc4200d59a0, 0xc42015cea0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:266 +0x7e
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc4200d59a0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:249 +0x662
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:64 +0x300
```

**Comment by 42wim** [comment]
Hi, is this something you can reproduce ? or it just happened once ?

**Comment by badporcupine** [comment]
Hi, yes, it happens after a few hours. I'll let you know once I have the debug log.

Great little software btw, keep up the good work 🙂

**Comment by badporcupine** [comment]
Ok, got some debug info. Note that I masked the messages.

```
DEBU[2017-05-26T11:02:24+03:00] &model.Post{Id:"3jjdd9kh1bg95p5au9b76fweyo", CreateAt:1495785744672, UpdateAt:1495785744672, EditAt:0, DeleteAt:0, UserId:"pugz8zytcbf6ipqommshdg4sje", ChannelId:"usg3hqakkjr37y9zd3ya8enaty", RootId:"", ParentId:"", OriginalId:"", Message:"****", Type:"", Props:model.StringInterface{}, Hashtags:"", Filenames:model.StringArray(nil), FileIds:model.StringArray(nil), PendingPostId:"pugz8zytcbf6ipqommshdg4sje:1495785744552", HasReactions:false}  module=matterircd
DEBU[2017-05-26T11:02:24+03:00] posting lastview "usg3hqakkjr37y9zd3ya8enaty"  module=matterclient
DEBU[2017-05-26T11:02:24+03:00] in handleWsMessage                            module=matterircd
DEBU[2017-05-26T11:02:25+03:00] WsReceiver: model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"parent_id":"", "user_id":"d4gyzyop3jy5jfzx4zu3pr771y"}, Broadcast:(*model.WebsocketBroadcast)(0xc420263940), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-05-26T11:02:25+03:00] WsReceiver: &model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"parent_id":"", "user_id":"d4gyzyop3jy5jfzx4zu3pr771y"}, Broadcast:(*model.WebsocketBroadcast)(0xc420263940), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2017-05-26T11:02:25+03:00] in handleWsMessage                            module=matterircd
DEBU[2017-05-26T11:02:27+03:00] WsReceiver: model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"parent_id":"", "user_id":"dxt1gc8rptr9dqhkkotbf433ga"}, Broadcast:(*model.WebsocketBroadcast)(0xc4201a2240), PreComputeJson:[]uint8(nil)}  module=matterclient
DEBU[2017-05-26T11:02:27+03:00] WsReceiver: &model.WebSocketEvent{Event:"typing", Data:map[string]interface {}{"parent_id":"", "user_id":"dxt1gc8rptr9dqhkkotbf433ga"}, Broadcast:(*model.WebsocketBroadcast)(0xc4201a2240), PreComputeJson:[]uint8(nil)}  module=matterircd
DEBU[2017-05-26T11:02:27+03:00] in handleWsMessage                            module=matterircd
DEBU[2017-05-26T11:02:28+03:00] WsReceiver: model.WebSocketEvent{Event:"post_edited", Data:map[string]interface {}{"post":"{\"id\":\"g4ityaz8mbb9fy59ig8nyckime\",\"create_at\":1495785665594,\"update_at\":1495785748050,\"edit_at\":1495785748049,\"delete_at\":0,\"is_pinned\":false,\"user_id\":\"jadrcjcrhj8dznkoebbqoonnho\",\"channel_id\":\"eim5b3i58in6irepzgeezknoir\",\"root_id\":\"\",\"parent_id\":\"\",\"original_id\":\"\",\"message\":\"********\",\"type\":\"\",\"props\":{},\"hashtags\":\"\",\"pending_post_id\":\"\"}"}, Broadcast:(*model.WebsocketBroadcast)(0xc4201a2340), PreComputeJson:[]uint8(nil)}  module=matterclient
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7b238f]

goroutine 104 [running]:
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).parseActionPost(0xc4202dedc0, 0xc420488c60)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:299 +0x4bf
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).parseMessage(0xc4202dedc0, 0xc420488c60)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:266 +0x7e
github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc4202dedc0)
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:249 +0x662
created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
        /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:64 +0x300
```

**Comment by 42wim** [comment]
I think I got a fix for it. Can you build from master and test ?

**Comment by badporcupine** [comment]
Sure. Has been working great for two days now. I'd say it's fixed. Thanks a lot!

**Comment by 42wim** [comment]
Thanks for testing and reporting
