### ISSUE TITLE
SEGSEGV when channel cannot be found

### ISSUE THREAD

**Issue by pieterlexis** [42wim/matterircd#99]
Hi,

I just had a segfault when running matterircd 0.11.4 connected to mattermost team edition 3.9.0.

Here's the error logged by mattermost and matterircd:

```
Jun 12 15:25:21 mattermost-host platform[30591]: [2017/06/12 15:25:21 UTC] [EROR] /api/v3/teams/p1gqez5gj3frjrxhafsdc45iha/channels/bxm3eth4djfcxggeiofxsk1sdr/:getChannel code=500 rid=fab337h98pf65rnsxsjrenkstr uid=4ux8atkiybrr3c87k63pzu5bgh ip=2a03:b0c0:2:d0::1392:e001 There is no channel with channel_id=bxm3eth4djfcxggeiofxsk1sdr on team with team_id=p1gqez5gj3frjrxhafsdc45iha [details: ]
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: panic: runtime error: invalid memory address or nil pointer dereference
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x7b238f]
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: goroutine 114 [running]:
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).parseActionPost(0xc4200779a0, 0xc420500f00)
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:299 +0x4bf
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).parseMessage(0xc4200779a0, 0xc420500f00)
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:266 +0x7e
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient.(*MMClient).WsReceiver(0xc4200779a0)
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/matterbridge/matterclient/matterclient.go:249 +0x662
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: created by github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit.(*User).loginToMattermost
Jun 12 15:25:21 mattermost-host matterircd-0.11.4[29027]: /go/src/github.com/42wim/matterircd/vendor/github.com/42wim/mm-go-irckit/mmuser.go:64 +0x300
Jun 12 15:25:21 mattermost-host systemd[1]: matterircd.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 12 15:25:21 mattermost-host systemd[1]: Unit matterircd.service entered failed state.
```

I don't know what triggered the channel look up though.

If you need more information, let me know.

**Comment by 42wim** [comment]
This was fixed in master  (see #97).
I just released v0.11.5 (https://github.com/42wim/matterircd/releases/tag/v0.11.5) with the fix in it.
